name: CI/CD Deployment to GKE

on:
  push:
    branches:
      - main

env:
  PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
  GKE_CLUSTER: "my-cluster"
  GKE_REGION: "us-central1"
  DEPLOYMENT_NAME: "mlops-app"
  REPOSITORY: "us-central1-docker.pkg.dev/apt-momentum-355109/my-repo"
  IMAGE: "us-central1-docker.pkg.dev/apt-momentum-355109/my-repo/mlops-app"

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      # ✅ Auth with Google Cloud
      - name: Authenticate with Google Cloud
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      # ✅ Setup gcloud SDK
      - name: Set up gcloud SDK
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}

      # ✅ Install GKE Auth Plugin
      - name: Install GKE gcloud auth plugin
        run: |
          sudo apt-get update
          sudo apt-get install -y google-cloud-sdk-gke-gcloud-auth-plugin

      # ✅ Configure Docker
      - name: Configure Docker for Artifact Registry
        run: gcloud auth configure-docker us-central1-docker.pkg.dev

      # ✅ Build & Push image
      - name: Build and Push Image
        run: |
          docker build -t $IMAGE:$GITHUB_SHA .
          docker push $IMAGE:$GITHUB_SHA

      # ✅ Get cluster credentials
      - name: Get GKE Credentials
        run: gcloud container clusters get-credentials $GKE_CLUSTER --region $GKE_REGION --project $PROJECT_ID

      # ✅ Deploy to Kubernetes
      - name: Deploy to GKE
        run: |
          kubectl apply -f kubernetes-deployment.yaml --validate=false
          kubectl set image deployment/$DEPLOYMENT_NAME $DEPLOYMENT_NAME=$IMAGE:$GITHUB_SHA
